name: month_year_picker_example
description: Shows example on how to use the month_year_picker package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  month_year_picker:
    path: ..

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
