name: month_year_picker
description: The month year picker inspired by the Flutter's date picker design.
version: 0.5.0+1
homepage: https://github.com/zulfahmi93/month-year-picker

environment:
  sdk: ^3.8.0
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_lints: ^4.0.0
